rules:
  color-no-invalid-hex: true

  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true

  function-calc-no-invalid: true
  function-linear-gradient-no-nonstandard-direction: true

  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true

  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown: true

  no-descending-specificity: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true

  string-no-newline: true
  unit-no-unknown: true
  property-no-unknown: true
  keyframe-declaration-no-important: true
  block-no-empty: true
  media-feature-name-no-unknown: true
  at-rule-no-unknown: true
  comment-no-empty: true

  # limit language features
  color-named: never
  shorthand-property-no-redundant-values:
    - true
    - severity: warning
  declaration-block-no-redundant-longhand-properties:
    - true
    - severity: warning
  declaration-no-important: true
  no-unknown-animations: true

  # style
  indentation: 2
  linebreaks: unix
  no-eol-whitespace: true
  no-missing-end-of-source-newline: true
  no-empty-first-line: true
  unicode-bom: never

  color-hex-length: short
  font-family-name-quotes: always-unless-keyword
  font-weight-notation: numeric
  number-no-trailing-zeros: true
  string-quotes: double
  length-zero-no-unit: true
  comment-whitespace-inside: always

  ## case
  color-hex-case: lower
  unit-case: lower
  value-keyword-case: lower
  property-case: lower

  ## decl
  declaration-bang-space-after: never
  declaration-bang-space-before: always

  declaration-colon-newline-after: always-multi-line
  declaration-colon-space-after: always
  declaration-colon-space-before: never

  ## decl-block
  declaration-block-semicolon-newline-after: always-multi-line
  declaration-block-semicolon-newline-before: never-multi-line

  # declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never

  declaration-block-trailing-semicolon: always

  ## selector
  selector-attribute-brackets-space-inside: never
  selector-attribute-quotes: always
  selector-descendant-combinator-no-non-space: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  selector-type-case: lower

  ## selector list
  selector-list-comma-newline-after: always-multi-line
  selector-list-comma-newline-before: never-multi-line

  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never

  ## block
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-before: always-multi-line

  # block-closing-brace-space-after: always-single-line
  block-closing-brace-space-before: always-single-line

  block-opening-brace-newline-after: always-multi-line
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always

  ## media feature
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never

  media-feature-name-case: lower
  media-feature-parentheses-space-inside: never

  ## media query
  media-query-list-comma-newline-after: always-multi-line
  media-query-list-comma-newline-before: never-multi-line

  media-query-list-comma-space-after: always-single-line
  media-query-list-comma-space-before: never

  ## value
  value-list-comma-newline-after: always-multi-line
  value-list-comma-newline-before: never-multi-line

  value-list-comma-space-after: always
  value-list-comma-space-before: never

  ## @rule
  at-rule-name-case: lower
  at-rule-name-space-after: always-single-line
  at-rule-semicolon-space-before: never

  ## function
  function-name-case: lower
  function-url-quotes: always
  function-whitespace-after: always

  function-comma-newline-after: always-multi-line
  function-comma-newline-before: never-multi-line

  function-comma-space-after: always
  function-comma-space-before: never

  function-parentheses-newline-inside: always-multi-line
  function-parentheses-space-inside: never
